---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-node
    managed-by: code-2020-plugin
  name: hello-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-node
      managed-by: code-2020-plugin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-node
        managed-by: code-2020-plugin
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        imagePullPolicy: Always
        name: echoserver

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-node
    managed-by: code-2020-plugin
  name: hello-node
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-node
    managed-by: code-2020-plugin
  sessionAffinity: None
  type: ClusterIP

